usr/lib/python2.7/dist-packages/lsm/__init__.*
usr/lib/python2.7/dist-packages/lsm/external*
usr/lib/python2.7/dist-packages/lsm/_client.*
usr/lib/python2.7/dist-packages/lsm/_common.*
usr/lib/python2.7/dist-packages/lsm/_local_disk.*
usr/lib/python2.7/dist-packages/lsm/_data.*
usr/lib/python2.7/dist-packages/lsm/_iplugin.*
usr/lib/python2.7/dist-packages/lsm/_pluginrunner.*
usr/lib/python2.7/dist-packages/lsm/_transport.*
usr/lib/python2.7/dist-packages/lsm/version.*
usr/lib/python2.7/dist-packages/lsm/plugin/__init__.*

usr/lib/python2.7/dist-packages/lsm/plugin/sim/__init__.*
usr/lib/python2.7/dist-packages/lsm/plugin/sim/simulator.*
usr/lib/python2.7/dist-packages/lsm/plugin/sim/simarray.*

usr/lib/python2.7/dist-packages/lsm/lsmcli/__init__.*
usr/lib/python2.7/dist-packages/lsm/lsmcli/data_display.*
usr/lib/python2.7/dist-packages/lsm/lsmcli/cmdline.*
etc/lsm/pluginconf.d/sim.conf

usr/lib/python2.7/dist-packages/lsm/plugin/smispy/__init__.*
usr/lib/python2.7/dist-packages/lsm/plugin/smispy/smis.*
usr/lib/python2.7/dist-packages/lsm/plugin/smispy/dmtf.*
usr/lib/python2.7/dist-packages/lsm/plugin/smispy/utils.*
usr/lib/python2.7/dist-packages/lsm/plugin/smispy/smis_common.*
usr/lib/python2.7/dist-packages/lsm/plugin/smispy/smis_cap.*
usr/lib/python2.7/dist-packages/lsm/plugin/smispy/smis_sys.*
usr/lib/python2.7/dist-packages/lsm/plugin/smispy/smis_pool.*
usr/lib/python2.7/dist-packages/lsm/plugin/smispy/smis_disk.*
usr/lib/python2.7/dist-packages/lsm/plugin/smispy/smis_vol.*
usr/lib/python2.7/dist-packages/lsm/plugin/smispy/smis_ag.*

usr/lib/python2.7/dist-packages/lsm/plugin/ontap/__init__.*
usr/lib/python2.7/dist-packages/lsm/plugin/ontap/na.*
usr/lib/python2.7/dist-packages/lsm/plugin/ontap/ontap.*

usr/lib/python2.7/dist-packages/lsm/plugin/targetd/__init__.*
usr/lib/python2.7/dist-packages/lsm/plugin/targetd/targetd.*

usr/lib/python2.7/dist-packages/lsm/plugin/nstor/__init__.*
usr/lib/python2.7/dist-packages/lsm/plugin/nstor/nstor.*

usr/lib/python2.7/dist-packages/lsm/plugin/megaraid/__init__.*
usr/lib/python2.7/dist-packages/lsm/plugin/megaraid/megaraid.*
usr/lib/python2.7/dist-packages/lsm/plugin/megaraid/utils.*
etc/lsm/pluginconf.d/megaraid.conf

usr/lib/python2.7/dist-packages/lsm/plugin/hpsa/__init__.*
usr/lib/python2.7/dist-packages/lsm/plugin/hpsa/hpsa.*
usr/lib/python2.7/dist-packages/lsm/plugin/hpsa/utils.*
etc/lsm/pluginconf.d/hpsa.conf
